### ISSUE TITLE
Error: NetWeaver DLLs need to be in PATH ?

### ISSUE THREAD

**Issue by clint2627** [dbosoft/YaNco#59] opened 2021-05-04 21:39 UTC
Getting the below error from a .net core web api app. Do the net weaver dlls need to be configured in PATH ?

![image](https://user-images.githubusercontent.com/67486268/117073215-36218c80-acf7-11eb-827d-21996879e370.png)

**Comment by clint2627** [comment] 2021-05-05 13:33
Where should these DLLs be located in relation to the output directory ?

**Comment by fw2568** [comment] 2021-05-05 13:39
all dlls from nwrfcsdk lib folder should be copied to output directory of executables. 
e. g. bin\Debug\netcoreapp3.1 for Debug of a netcoreapp 3.1.

**Comment by clint2627** [comment] 2021-05-05 13:57
so a little more info. It looks like I'm running into an issue with .net core 2.1. Are there any known issues with core 2.1 ?

**Comment by clint2627** [comment] 2021-05-05 14:05
No I think I was wrong. core 2.1 and core 3.1 both give me that error saying those DLLs should be in PATH

**Comment by fw2568** [comment] 2021-05-05 14:09
Problems like this are typical related to the point that nwrfcsdk is platform specific (this also applies to x64/x86). While you are normally don't have to care on .NET if you are running a x64 or a x86 process you have to if you use a C++ dll like the sdk.

therefore we typical use

`    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>`

in project sdk file. 

- I'm wondering how you caused this popup. Are you running in console mode, Krestrel or IIS? 
- Are the icu*.dll actually in the output directoy? 
- Have you used x64 nwrfcsdk or x86 sdk?

**Comment by clint2627** [comment] 2021-05-05 14:25
Good questions.

I'm in Visual Studio 2019 using IIS Express. However, I will eventually need this to work in an IIS environment, and a kubernetes environment.

The icu dlls are in the output directory.

I downloaded the x64 version of nwrfcsdk. Is there any way I can confirm that ? Should I be using the x86 version?

A little more info. Everything seemed to work in a core 3.1 console app when I went thru your blog step by step. What I'm trying to do now is get it to work in a core 2.1 web api application.

**Comment by fw2568** [comment] 2021-05-05 14:53
let me have a look, I will add some samples for these platforms (docker instead kubernetes, but should work too).

**Comment by fw2568** [comment] 2021-05-05 15:52
Ok, another collegue has told me that it is caused by IIS process mode. 

IIS in in-process mode will not load the libraries, either

- switch IIS express to Hosting Model = Out-of-process
- use Program profile

Docker / Kubernetes will not use IIS at all, but launches in program mode. So there it will work out of the box, but keep in mind that you have to provide nwrfcsdk linux lib in container.

**Comment by clint2627** [comment] 2021-05-05 15:59
ok thanks for the heads up. I didn't know there was a linux specific version of the nwrfcsdk DLLs. I guess I need to log back into SAP and see all the available downloads.

**Comment by clint2627** [comment] 2021-05-05 18:27
is the Hosting Model issue specific to net core ? Do I need to worry about that with an asp.net webforms project?

**Comment by fw2568** [comment] 2021-05-05 20:18
You don't have to worry. I have reviewed this topic again and finally it can be implemented in a way that work with any process mode / platform.

Please have a look at the new [samples for aspnetcore](https://github.com/dbosoft/YaNco/tree/master/samples). In Program.cs there is a call to a helper set sets the PATH variable (or LD_LIBRARY_PATH on Linux/MacOs):

https://github.com/dbosoft/YaNco/blob/10d8bae5846b1724472d72f3addb6a546f18eeaa/samples/netcore3.1/SAPWebAPI/Program.cs#L17

https://github.com/dbosoft/YaNco/blob/10d8bae5846b1724472d72f3addb6a546f18eeaa/samples/WebApi.Shared/RfcLibraryHelper.cs#L8-L16

I have tested this with .net 471, aspnetcore 2.1 and aspnetcore 3.1. Except for IIS Express in-proc mode and aspnetcore 2.1 it will also work on Windows without setting the path. So behavoir was at least different for .NET Core 2.1. However if you use logic like in the sample you can make sure that it will work in any environment.

### Containers

Please note that this don't work for linux containers. Here you have to set the environment variable 

`LD_LIBRARY_PATH = /app `

for the container. /app is the default path for a dockerfile created in Visual Studio.

### Debug Configuration / Launch Settings

In Debug Configuration the logic for containers has changed in Visual Studio 2019, as it will not rebuild the dockerfile in Debug config. 

Instead you can just add it to the launch settings:

https://github.com/dbosoft/YaNco/blob/10d8bae5846b1724472d72f3addb6a546f18eeaa/samples/netcore3.1/SAPWebAPI/Properties/launchSettings.json#L32-L35

**Comment by clint2627** [comment] 2021-05-05 20:52
that is a lot to unpack. I'm a little confused on the Linux part. Sounds like on a windows machine the variable name is PATH. On a Linux machine the variable name is LD_LIBRARY_PATH

However, this is not true in a kubernetes environment? The Linux pods in kubernetes the variable name needs to be /app ?

If so, can i change this

if(!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                pathVariableName = "LD_LIBRARY_PATH";

to this?

if(!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                pathVariableName = "/app";

**Comment by clint2627** [comment] 2021-05-05 20:54
In framework 4.7.2 I get a different error. The DLLs are in bin folder. Is it again looking in PATH location for the DLLs ?


![image](https://user-images.githubusercontent.com/67486268/117207947-2cad2880-adba-11eb-9d40-86afd12ebc12.png)

**Comment by fw2568** [comment] 2021-05-05 20:57
looks like you are trying to load a x86 library into a x64 process (or x64 into x86 process). See my first answer:

https://github.com/dbosoft/YaNco/issues/59#issuecomment-832718977

**Comment by fw2568** [comment] 2021-05-05 21:06
> if(!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
> pathVariableName = "LD_LIBRARY_PATH";
> 
> to this?
> 
> if(!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
> pathVariableName = "/app";

no. Variable name is always **LD_LIBRARY_PATH** on Linux. 
The point here is, that setting variable value within the running container has no effect. Probably this is a security feature of containers.

**Comment by clint2627** [comment] 2021-05-05 21:06
> looks like you are trying to load a x86 library into a x64 process (or x64 into x86 process). See my first answer:
> 
> [#59 (comment)](https://github.com/dbosoft/YaNco/issues/59#issuecomment-832718977)

OK I will download latest of each version and try both.

**Comment by clint2627** [comment] 2021-05-05 21:09
> > if(!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
> > pathVariableName = "LD_LIBRARY_PATH";
> > to this?
> > if(!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
> > pathVariableName = "/app";
> 
> no. Variable name is always **LD_LIBRARY_PATH** on Linux.
> The point here is, that setting variable value within the running container has no effect. Probably this is a security feature of containers.

So does that mean the DLLs won't work in containers?

**Comment by clint2627** [comment] 2021-05-05 21:27
> looks like you are trying to load a x86 library into a x64 process (or x64 into x86 process). See my first answer:
> 
> [#59 (comment)](https://github.com/dbosoft/YaNco/issues/59#issuecomment-832718977)

I've tried both x64 and x86 DLLs and get same error. Do you have any samples of .net framework web application running these DLLs ?

**Comment by fw2568** [comment] 2021-05-05 21:33
> So does that mean the DLLs won't work in containers?

no, that just means that you have to set the variable, e.g. in dockerfile: 

`ENV LD_LIBRARY_PATH=/app`

**Comment by fw2568** [comment] 2021-05-05 21:49
https://github.com/dbosoft/YaNco/tree/master/samples/net472/SAPWebAPI

this is ASPNET Core 2.1 running on .NET 4.72

however if you mean classic ASP.NET: that has never been tested, and I would not expect it to work as library support starts with .NET Framework 4.71.

**Comment by clint2627** [comment] 2021-05-06 16:05
I am trying to use this in these two scenarios:

1. ASP.NET WebForms application targeting .Net Framework 4.7.2 - hosted in an AWS windows server via IIS
2. Web Api MVC application targeting .Net Core 3.1 - Kubernetes environment with Linux pods

I got #2 running locally once I set this in the cproj file:

<AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>

However this is on my local windows machine with IIS Express. According to your previous comments it sounds like I will need to use Linux specific ICU*.dll for the Kubernetes environment. And it also sounds like I will have to modify docker file to set ENV LD_LIBRARY_PATH=/app

#1 however, I can't get passed the error I posted before:

![image](https://user-images.githubusercontent.com/67486268/117329496-4ef68300-ae5a-11eb-8486-9c8cb98fc517.png)

I've tried both x86 and x64 version of the DLLs and get the same error. And I have verified the DLLs are in the output directory (bin). I'm wondering if I need to programmatically set PATH like you described above in your code sample.

**Comment by fw2568** [comment] 2021-05-06 17:13
Ok, understood. 
First: we have to be careful about what we are talking. The PATH environment variable is a requirement of SAPNWRFC as it itself depends on the ICU libraries. To lookup these libraries it requires PATH variable or LD_LIBRARY_PATH to be set. 

In case of the ASP.NET application it already fails to load the sapnwrfc library. So for this environment forget the PATH topic for now. 

The error "`Could not load file or assembly … An attempt was made to load a program with an incorrect format (System.BadImageFormatException)`"is always caused by a x86 / x64 mismatch. 

So please your hosting settings for IIS / IIS Express, to make sure that they use a x64 process model if you load the x64 sapnwrfc.dll.

see also: https://stackoverflow.com/questions/11370344/could-not-load-file-or-assembly-an-attempt-was-made-to-load-a-program-with-a

**Comment by clint2627** [comment] 2021-05-06 20:50
Anything else I could be missing?

![image](https://user-images.githubusercontent.com/67486268/117363853-c5a77680-ae82-11eb-93cb-18a252e20855.png)

**Comment by fw2568** [comment] 2021-05-07 14:57
I have create a sample WebForms project that loads the library sucessfully:

https://github.com/dbosoft/YaNco/blob/352cc377f6558afdebf16b49d50bdc000df194c0/samples/webforms/SAPWebForms/Default.aspx.cs#L11-L31

it cannot do anything except loading nwrfc dll but thats all we need here. 

During setup of project I first had same problem as you. But I could solve it by switching "Bitness" setting in Project settings / Web to x64.

However then the next problem occured. The web projects tried to load the DLL as .NET assembly and was of course failing because it is a C++ DLL.
So finally I found out that this could also be solved by setting the PATH variable to the folder with DLLs:
https://stackoverflow.com/questions/7996263/how-do-i-get-iis-to-load-a-native-dll-referenced-by-my-wcf-service

Or you can copy it to c:\windows\system32 (or c:\windows\syswow64 of you would like to use the x86 library). 

**So to summarize this:**
For WebForms do not copy the DLLs to the bin directory. 

Instead create a folder somewhere else and include this in the system PATH variable. Then you have also set the path for the ICU libs.

**Comment by fw2568** [comment] 2021-05-09 13:52
WebForms sample has been update todo something useful and merged into master:

https://github.com/dbosoft/YaNco/blob/0f57fe4e530d169c33a6f939641e8a45e577c899/samples/webforms/SAPWebForms/Default.aspx.cs#L18-L47

**Comment by fw2568** [comment] 2021-05-17 16:29
as working in updated samples, I close this issue

**Closed by fw2568** 2021-05-17 16:29 UTC
